---
.gitlab-ci.yml:
  delete: true

.gitignore:
  paths:
    - .ruby-version

.yardopts:
  delete: true

appveyor.yml:
  delete: true

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"

Rakefile:
  changelog_user: 'dev-sec'
  changelog_project: 'puppet-os-hardening'
  changelog_since_tag: '1.1.1'
