---
bundler_args: --without system_tests
cache: bundler
dist: trusty
language: ruby

notifications:
  email: false

services:
  - docker

before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v

rvm:
  - 2.5.1

script:
  - 'bundle exec rake $CHECK'

jobs:
  include:
    - name: "Syntax & Lint checks"
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    - name: "Unit tests (Puppet 6)"
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
    - name: "Unit tests (Puppet 5)"
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
    - stage: integration
      name: "Integration test (CentOS 7)"
      env: INSTANCE=centos-7 CHECK=kitchen
    - name: "Integration test (Debian 8)"
      env: INSTANCE=debian-8 CHECK=kitchen
    - name: "Integration test (Ubuntu 16.04)"
      env: INSTANCE=ubuntu-16-04 CHECK=kitchen
